name: jupyterlite-build
channels:
  - conda-forge
dependencies:
  - python=3.11
  - bqplot
  - ipycanvas >=0.9.1
  - ipyleaflet
  - ipympl >=0.8.2
  - ipywidgets >=8.1.3,<9
  - jupyterlab >=4.4.5,<4.5
  - jupyterlab-fasta >=3.3.0,<4
  - jupyterlab-geojson >=3.4.0,<4
  - jupyterlab-language-pack-fr-FR
  - jupyterlab-language-pack-zh-CN
  - jupyterlab-night
  - jupyterlite-core =0.6.4
  - jupyterlite-pyodide-kernel =0.6.1
  - jupyterlite-terminal >=1.1.0,<1.2.0
  - notebook >=7.4.5,<7.5
  - pip
  - plotly >=6,<7
  - micromamba >=2.0.5,<3
  - nodejs =22
  - pip:
    - jupyterlab_miami_nights
    - ipyevents >=2.0.1

